version: "3.9"

services:

  lynbot:

    container_name: lynbot

    image: ghcr.io/lynbean/lynbot:latest

    restart: always

    volumes:
      - data:/root/.kim/lynbot

    environment:
      DISCORD_TOKEN: "INSERT BOT TOKEN HERE"
      OPENAI_KEY: "INSERT OPENAI KEY HERE"

volumes:
  data:
