version: "3.9"

services:

  lynbot:

    container_name: lynbot

    image: ghcr.io/lynbean/lynbot:latest

    restart: always

    volumes:
      - ./lynbot_data:/lynbot/data

    ports:
      - 27017:27017 # MongoDB (REQUIRED)
